//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBox.Api.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Highscore
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public double ScorePercent { get; set; }
        public int TimeElapsedSeconds { get; set; }
        public string UserId { get; set; }
        public System.DateTime EndTime { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
